# numpy

In [4]:
import numpy as np

## array

In [17]:
prs_ht = [177.7, 175.4, 173.6, 178.0]
prs_wt = [76, 77, 75, 79, 79]

prs_ht = np.array(prs_ht)
prs_wt = np.array(prs_wt)
type(prs_wt)
prs_ht[[1,3]]

array([175.4, 178. ])

In [13]:
## 2d array
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(arr)
# arr[1][1] === arr[1,1]
arr[:, 1]

array([2, 5, 8])

In [25]:
## Slicing
arr = np.array([
    [101, 131, 122, 113, 143],
    [145, 165, 137, 318, 193],
    [240, 241, 252, 253, 324],
    [225, 126, 727, 928, 129]
])
arr[1:, 2:4]

array([[137, 318],
       [252, 253],
       [727, 928]])

In [51]:
## Operations
### Addition
arr1 = np.array([140, 133, 150, 148])
arr2 =np.array([5,5,5,5]) # np.arange(1,5)
# arr1 +5
arr1 + arr2

array([145, 138, 155, 153])

In [39]:
### Multi
arr1 * arr2
arr1 ** arr2
arr1 / arr2
arr1 % arr2

array([0, 1, 0, 0])

In [43]:
### Comparison and Filtering
arr_bool = arr1 > 140
arr_bool
arr1[arr_bool]

array([150, 148])

In [48]:
## Arithmetic Operation Funs
arr1.sum()
arr1.min()
np.power(arr1, 2)

array([19600, 17689, 22500, 21904])

In [67]:
## Contatentions
# 1d
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
np.concatenate([arr1,arr2]) # axis: 0 [default]

array([1, 2, 3, 4, 5, 6])

In [68]:
### 2d
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
np.concatenate([my_array, my_array], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [83]:
## Splitting
### split()
arr = np.arange(10)
# np.split(arr, 2)
np.split(arr, [5, 7])

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [81]:
### array_split()
np.array_split(arr, 3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [87]:
### vsplit hsplit
arr = np.arange(20).reshape(4,5)
np.vsplit(arr, 2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [92]:
### hsplit
arr = np.arange(16).reshape(4,4)
np.hsplit(arr, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]